version: '3.8'

services:
db:
    image: postgres:15-alpine 
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: orzelkj
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: backend:latest
    container_name: backend_container
    ports:
      - "5000:8080" 
    restart: always

  frontend:
    image: frontend:latest
    container_name: frontend_container
    ports:
      - "3000:80" 
    depends_on:
      - backend
    restart: always
